services:

  # ============================================================
  # DATABASES
  # ============================================================

  postgres:
    image: postgres:16
    container_name: hms-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"


  mongodb:
    image: mongo:7
    container_name: hms-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================================================
  # EUREKA
  # ============================================================

  eureka-server:
    build: ./backend/eureka-server/eureka-server
    container_name: hms-eureka
    ports:
      - "8761:8761"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8761/"
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  # ============================================================
  # API GATEWAY
  # ============================================================

  gateway-service:
    build: ./backend/gateway-service/gateway-service
    container_name: hms-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy


  # ============================================================
  # AUTH SERVICE
  # ============================================================

  auth-service:
    build: ./backend/auth-service/auth-service
    container_name: hms-auth
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy


  # ============================================================
  # PATIENT SERVICE
  # ============================================================

  patient-service:
    build: ./backend/patient-service/patient-service
    container_name: hms-patient
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_started


  # ============================================================
  # DOCTOR SERVICE
  # ============================================================

  doctor-service:
    build: ./backend/doctor-service/doctor-service
    container_name: hms-doctor
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy


  # ============================================================
  # APPOINTMENT SERVICE
  # ============================================================

  appointment-service:
    build: ./backend/appointment-service/appointment-service
    container_name: hms-appointment
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy


  # ============================================================
  # BILLING SERVICE
  # ============================================================

  billing-service:
    build: ./backend/billing-service/billing-service
    container_name: hms-billing
    ports:
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy


  # ============================================================
  # INVENTORY SERVICE
  # ============================================================

  inventory-service:
    build: ./backend/inventory-service/inventory-service
    container_name: hms-inventory
    ports:
      - "8086:8086"
    depends_on:
      mongodb:
        condition: service_healthy
      eureka-server:
        condition: service_healthy


  # ============================================================
  # NOTIFICATION SERVICE
  # ============================================================

  notification-service:
    build: ./backend/notification-service/notification-service
    container_name: hms-notification
    ports:
      - "8087:8087"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy


  # ============================================================
  # PRESCRIPTION SERVICE
  # ============================================================

  prescription-service:
    build: ./backend/prescription-service/prescription-service
    container_name: hms-prescription
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy


  # ============================================================
  # AI TRIAGE SERVICE
  # ============================================================

  ai-triage-service:
    build: ./backend/ai-triage-service
    container_name: hms-ai-triage
    ports:
      - "5006:5006"


# ==============================================================
# VOLUMES
# ==============================================================

volumes:
  postgres_data:
  mongodb_data: