server:
  port: 8084

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:postgresql://localhost:5432/doctordb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "super_secure_jwt_secret_key_32char_min"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
