server:
  port: 8082

spring:
  application:
    name: patient-service
    
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/hmsdb
    username: hmsuser
    password: HmsP@ssw0rd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  secret: "9vi2a=A2(L!bm#=0tedk%fq1~!u^q+aF"

aws:
  s3:
    bucket-name: your-hms-ehr-bucket
    region: us-east-1
    access-key: dummy
    secret-key: dummy
    enabled: false
   
  sns:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Optional Swagger Config (springdoc-openapi)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html