server:
  port: 8082

spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hmsdb
    username: hmsuser
    password: HmsP@ssw0rd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

aws:
  s3:
    region: us-east-1
    bucket-name: ehr-storage-bucket
    access-key: dummy
    secret-key: dummy
    enabled: false

  sns:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  #  secret: "9vi2a=A2(L!bm#=0tedk%fq1~!u^q+aF"
  secret: "2354da8ebd54655ec06ae826cecaf1d2b7bc377f1c765f12383e95853a3b78d2"
