server:
  port: 8086

spring:
  application:
    name: inventory-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/hms_inventory
      database: inventory_item

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
