# ===============================
# 🔔 NOTIFICATION SERVICE (Example Config)
# ===============================

server:
  port: 8087

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hmsdb
    username: hmsuser
    password: ""   # Leave empty or use env variable
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ===============================
# 🔗 EUREKA CLIENT
# ===============================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# ===============================
# 📧 EMAIL (SendGrid)
# ===============================
sendgrid:
  api-key: "REPLACE_WITH_YOUR_API_KEY"

# ===============================
# 📱 SMS (Twilio)
# ===============================
twilio:
  account-sid: "REPLACE_WITH_YOUR_ACCOUNT_SID"
  auth-token: "REPLACE_WITH_YOUR_AUTH_TOKEN"
  from-number: "+1234567890"

# ===============================
# 🔐 JWT CONFIG (Optional)
# ===============================
jwt:
  # secret: "REPLACE_WITH_YOUR_JWT_SECRET"

# ===============================
# 📜 SWAGGER / API DOCS
# ===============================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
