server:
  port: 8084

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hmsdb
    username: hmsuser
    password: HmsP@ssw0rd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "super_secure_jwt_secret_key_32char_min"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
