openapi: 3.0.0
info:
  title: Billing Service API
  version: 1.0.0

paths:
  /bills:
    post:
      summary: Generate new invoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceDTO'
      responses:
        '201':
          description: Invoice created

  /bills/{patientId}:
    get:
      summary: Get invoices by patient ID
      parameters:
        - name: patientId
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: List of invoices

  /claims:
    post:
      summary: Submit insurance claim
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsuranceClaimDTO'
      responses:
        '201':
          description: Claim submitted

components:
  schemas:
    InvoiceDTO:
      type: object
      properties:
        patientId:
          type: integer
        amount:
          type: number
          format: double

    InsuranceClaimDTO:
      type: object
      properties:
        patientId:
          type: integer
        invoiceId:
          type: integer
        insurer:
          type: string