# ===============================
# 🌐 GATEWAY SERVICE (Example Config)
# ===============================

server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/patient-service/**
              filters:
                - StripPrefix=1
                - RewritePath=/patient-service/(?<segment>.*), /${segment}
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

            - id: doctor-service
              uri: lb://doctor-service
              predicates:
                - Path=/doctor-service/**
              filters:
                - StripPrefix=1
                - RewritePath=/doctor-service/(?<segment>.*), /${segment}
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

            - id: appointment-service
              uri: lb://appointment-service
              predicates:
                - Path=/appointment-service/**
              filters:
                - StripPrefix=1
                - RewritePath=/appointment-service/(?<segment>.*), /${segment}
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory-service/**
              filters:
                - StripPrefix=1
                - RewritePath=/inventory-service/(?<segment>.*), /${segment}
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notification-service/**
              filters:
                - StripPrefix=1
                - RewritePath=/notification-service/(?<segment>.*), /${segment}
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

            - id: billing-service
              uri: lb://billing-service
              predicates:
                - Path=/billing-service/**
              filters:
                - StripPrefix=1
                - RewritePath=/billing-service/(?<segment>.*), /${segment}
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

# ===============================
# 🔐 JWT CONFIGURATION
# ===============================
jwt:
  secret: "replace_with_your_secret_key"

# ===============================
# 🔗 EUREKA CLIENT
# ===============================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

# ===============================
# 📝 LOGGING
# ===============================
logging:
  level:
    org.springframework.security: DEBUG
    com.hms: DEBUG
